export enum CountryCodeEnum {
  Argentina = 'ar',
  Armenia = 'am',
  Australia = 'au',
  Austria = 'at',
  Azerbaijan = 'az',
  Bangladesh = 'bd',
  Belarus = 'by',
  Belgium = 'be',
  Belize = 'bz',
  Bolivia = 'bo',
  Brazil = 'br',
  Brunei = 'bn',
  Bulgaria = 'bg',
  Canada = 'ca',
  CanadaFrench = 'ca-fr',
  Chile = 'cl',
  China = 'cn',
  Colombia = 'co',
  CostaRica = 'cr', // 新增 Mexico Mirror Site Costa Rica By Cody.Yang 2024/08/20
  Croatia = 'hr',
  CzechRepublic = 'cz',
  Denmark = 'dk',
  Ecuador = 'ec',
  Egypt = 'arabic',
  EuropeanUnion = 'eu',
  Fiji = 'fj',
  Finland = 'fi',
  France = 'fr',
  Georgia = 'ge',
  Germany = 'de',
  Global = 'global',
  Greece = 'gr',
  Honduras = 'hn',
  HongKong = 'hk',
  Hungary = 'hu',
  India = 'in',
  Indonesia = 'id',
  Ireland = 'ie',
  Israel = 'il',
  Italy = 'it',
  Japan = 'jp',
  Jordan = 'jo',
  Kazakhstan = 'kz',
  Korea = 'kr',
  Laos = 'la',
  LatinAmerica = 'latam',
  Latvia = 'lv',
  Lithuania = 'lt',
  Luxembourg = 'lu',
  Malaysia = 'my',
  Mexico = 'mx',
  MiddleEast = 'persian',
  Moldova = 'md',
  Mongolia = 'mn',
  Netherlands = 'nl',
  NewZealand = 'nz',
  Nicaragua = 'ni',
  Norway = 'no',
  Pakistan = 'pk',
  Palestine = 'ps',
  Panama = 'pa',
  Paraguay = 'py',
  Peru = 'pe',
  Philippines = 'ph',
  Poland = 'pl',
  Portugal = 'pt',
  PuertoRico = 'pr',
  Romania = 'ro',
  Russia = 'ru',
  SaudiArabia = 'sa',
  Serbia = 'rs',
  Singapore = 'sg',
  SlovakRepublic = 'sk',
  Slovenia = 'si',
  SouthAfrica = 'za',
  Spain = 'es',
  SriLanka = 'lk',
  Sweden = 'se',
  Switzerland = 'ch',
  Taiwan = 'tw',
  Thailand = 'th',
  Turkey = 'tr',
  UnitedArabEmirates = 'ae',
  UnitedKingdom = 'uk',
  UnitedStates = 'us',
  Ukraine = 'ua',
  Uruguay = 'uy',
  Vietnam = 'vn',
}

export enum ProductCategoryKeyEnum {
  NoType = 0,
  Consumer = 1,
  Enterprise = 2,
}

export enum HttpStatusCode {
  BadRequest = 400,
  Forbidden = 403,
  NotFound = 404,
  InternalServerError = 500,
  BadGateway = 502,
  ServiceUnavailable = 503,
}

export enum BreakpointsEnum {
  DeviceBreakpoint = 960,
  DeviceBreakPoint768 = 768,
  DeviceBreakPointUiLibrary = 1024,
}

export enum EnvironmentConfigEnum {
  BrandStaging = 'brandstaging',
  BrandInternal = 'BrandInternal',
  OutTest = 'outtest',
  TestLocal = 'testlocal',
  GlobalAzureVm = 'globalazurevm',
  GlobalExternal = 'globalexternal',
  GlobalInternal = 'globalinternal',
}


